# Generated by Django 3.2.7 on 2021-09-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='accountNumber',
            field=models.CharField(default=1, max_length=100, verbose_name='Account Number'),
            preserve_default=False,
        ),
    ]
