# Generated by Django 3.2.7 on 2021-09-09 06:26

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('debtManager', '0002_debt_accountnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='payFrequency',
        ),
        migrations.AddField(
            model_name='debt',
            name='apr',
            field=models.FloatField(default=0.0, verbose_name='APR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='debtCompany',
            field=models.CharField(default='default', max_length=100, verbose_name='Company Name:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='debtCompanyAddress',
            field=models.CharField(default='default', max_length=100, verbose_name='Company Address:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='debtType',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('BL', 'Bank Loan'), ('LS', 'Loan Shark'), ('M', 'Mortgage'), ('CL', 'Car Loan')], default='default', max_length=2, verbose_name='Debt Type:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='dueDate',
            field=models.DateField(default=datetime.datetime.now(), verbose_name='Due Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Debt Nickname:'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='payAmount',
            field=models.FloatField(verbose_name='Minimum Payment Amount'),
        ),
    ]
