# Generated by Django 3.2.7 on 2021-09-08 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incomeManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='accountHolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
